version: "3"

services:
  kaggle:
    build:
     context: ./docker
     args:
       - HTTP_PROXY=$HTTP_PROXY
       - http_proxy=$http_proxy
       - HTTPS_PROXY=$HTTPS_PROXY
       - https_proxy=$https_proxy
       - FTP_PROXY=$FTP_PROXY
       - ftp_proxy=$ftp_proxy
       - NO_PROXY=$NO_PROXY
       - no_proxy=$no_proxy
    shm_size: "16gb"
    container_name: kaggle
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - HTTP_PROXY=$HTTP_PROXY
      - http_proxy=$http_proxy
      - HTTPS_PROXY=$HTTPS_PROXY
      - https_proxy=$https_proxy
      - FTP_PROXY=$FTP_PROXY
      - ftp_proxy=$ftp_proxy
      - NO_PROXY=$NO_PROXY
      - no_proxy=$no_proxy
    ports:
      - 8888:8888
    volumes:
      - $PWD/workspace:/home/kaggler/workspace
    working_dir: /home/kaggler/workspace
